version: "3.8"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
