INSERT INTO cards VALUES (default, 'Kozilek, Butcher of Truth', 'kozilek.jpg', '10', 'Legendary Creature — Eldrazi', 'When you cast this spell, draw four cards. Annihilator 4 (Whenever this creature attacks, defending player sacrifices four permanents.) When Kozilek, Butcher of Truth is put into a graveyard from anywhere, its owner shuffles their graveyard into their library.', '', '12/12', 'Michael Komarck', 'Double Masters', '2X2', 2, 'Mythic Rare');
INSERT INTO cards VALUES (default, 'Imperial Seal', 'imperial-seal.jpg', 'B', 'Sorcery', 'Search your library for a card, then shuffle and put that card on top. You lose 2 life.', 'Your presence at the palace this evening is required. — Letter from Queen Marchesa', '', 'Milivoj Ćeran', 'Double Masters', '2X2', 79, 'Mythic Rare');
INSERT INTO cards VALUES (default, 'Mana Vault', 'mana-vault.jpg', '1', 'Artifact', 'Mana Vault doesnt untap during your untap step. At the beginning of your upkeep, you may pay {4}. If you do, untap Mana Vault. At the beginning of your draw step, if Mana Vault is tapped, it deals 1 damage to you. {T}: Add {C}{C}{C}.', '', '', 'Christine Choi', 'Double Masters', '2X2', 308, 'Mythic Rare');
INSERT INTO cards VALUES (default, 'Emrakul, the Aeons Torn', 'emrakul.jpg', '15', 'Legendary Creature — Eldrazi', 'This spell can’t be countered. When you cast this spell, take an extra turn after this one. Flying, protection from spells that are one or more colors, annihilator 6. When Emrakul, the Aeons Torn is put into a graveyard from anywhere, its owner shuffles their graveyard into their library.', '', '15/15', 'Mark Tedin', 'Double Masters', '2X2', 1, 'Mythic Rare');
INSERT INTO cards VALUES (default, 'Llanowar Elves', 'llanowar-elves.jpg', 'G', 'Creature — Elf Druid', 'Tap: Add 1 green mana.', 'As patient and generous as life, as harsh and merciless as nature.', '1/1', 'Chris Rahn', 'Core Set 2019', 'M19', 314, 'Common');
INSERT INTO cards VALUES (default, 'Merfolk Pupil', 'merfolk-pupil.jpg', '1U', 'Creature — Merfolk Wizard', 'When Merfolk Pupil enters the battlefield, draw a card, then discard a card. {1}{U}, Exile Merfolk Pupil from your graveyard: Draw a card, then discard a card.', 'Maintaining a personal bubble is even more important when you have gills.', '1/1', 'Caroline Gariba', 'Jumpstart 2022', 'J22', 15, 'Common');
INSERT INTO cards VALUES (default, 'Goblin General', 'goblin-general.jpg', '1RR', 'Creature — Goblin Warrior', 'Whenever Goblin General attacks, Goblin creatures you control get +1/+1 until end of turn.', 'Lead, follow, or run around like crazy.', '1/1', 'Keith Parkinson', 'Vintage Masters', 'VMA', 165, 'Common');
INSERT INTO cards VALUES (default, 'A Good Day to Pie', 'a-good-day-to-pie.jpg', '1W', 'Instant', 'Tap up to two target creatures. Whenever you put a name sticker on a creature, you may return A Good Day to Pie from your graveyard to your hand.', '“What could be funnier than one big pie to the face? Unless … no. Could it be that simple?” — Pietra, Crafter of Clowns', '', 'Zoltan Boros', 'Unfinity', 'UNF', 12, 'Common');
INSERT INTO cards VALUES (default, 'Akroan Mastiff', 'akroan-mastiff.jpg', '3W', 'Creature — Hound', 'W, Tap: Tap target creature.', 'Even when many of the soldiers who guarded Akros were called away, its safety was never in doubt.', '2/2', 'Zoltan Boros', 'Journey into Nyx', 'JOU', 3, 'Common');

INSERT INTO legality VALUES (default, 1, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 1, 'Pioneer', FALSE);
INSERT INTO legality VALUES (default, 1, 'Modern', TRUE);
INSERT INTO legality VALUES (default, 1, 'Legacy', TRUE);
INSERT INTO legality VALUES (default, 1, 'Vintage', TRUE);
INSERT INTO legality VALUES (default, 1, 'Commander', TRUE);
INSERT INTO legality VALUES (default, 1, 'Oathbreaker', TRUE);
INSERT INTO legality VALUES (default, 1, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 1, 'Explorer', FALSE);
INSERT INTO legality VALUES (default, 1, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 1, 'Historic', FALSE);
INSERT INTO legality VALUES (default, 1, 'Pauper', FALSE);
INSERT INTO legality VALUES (default, 1, 'Penny', FALSE);

INSERT INTO legality VALUES (default, 2, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 2, 'Pioneer', FALSE);
INSERT INTO legality VALUES (default, 2, 'Modern', FALSE);
INSERT INTO legality VALUES (default, 2, 'Legacy', FALSE);
INSERT INTO legality VALUES (default, 2, 'Vintage', FALSE);
INSERT INTO legality VALUES (default, 2, 'Commander', TRUE);
INSERT INTO legality VALUES (default, 2, 'Oathbreaker', TRUE);
INSERT INTO legality VALUES (default, 2, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 2, 'Explorer', FALSE);
INSERT INTO legality VALUES (default, 2, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 2, 'Historic', FALSE);
INSERT INTO legality VALUES (default, 2, 'Pauper', FALSE);
INSERT INTO legality VALUES (default, 2, 'Penny', FALSE);

INSERT INTO legality VALUES (default, 3, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 3, 'Pioneer', FALSE);
INSERT INTO legality VALUES (default, 3, 'Modern', FALSE);
INSERT INTO legality VALUES (default, 3, 'Legacy', FALSE);
INSERT INTO legality VALUES (default, 3, 'Vintage', FALSE);
INSERT INTO legality VALUES (default, 3, 'Commander', TRUE);
INSERT INTO legality VALUES (default, 3, 'Oathbreaker', FALSE);
INSERT INTO legality VALUES (default, 3, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 3, 'Explorer', FALSE);
INSERT INTO legality VALUES (default, 3, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 3, 'Historic', FALSE);
INSERT INTO legality VALUES (default, 3, 'Pauper', FALSE);
INSERT INTO legality VALUES (default, 3, 'Penny', FALSE);

INSERT INTO legality VALUES (default, 4, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 4, 'Pioneer', FALSE);
INSERT INTO legality VALUES (default, 4, 'Modern', TRUE);
INSERT INTO legality VALUES (default, 4, 'Legacy', TRUE);
INSERT INTO legality VALUES (default, 4, 'Vintage', TRUE);
INSERT INTO legality VALUES (default, 4, 'Commander', FALSE);
INSERT INTO legality VALUES (default, 4, 'Oathbreaker', FALSE);
INSERT INTO legality VALUES (default, 4, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 4, 'Explorer', FALSE);
INSERT INTO legality VALUES (default, 4, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 4, 'Historic', FALSE);
INSERT INTO legality VALUES (default, 4, 'Pauper', FALSE);
INSERT INTO legality VALUES (default, 4, 'Penny', FALSE);

INSERT INTO legality VALUES (default, 5, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 5, 'Pioneer', TRUE);
INSERT INTO legality VALUES (default, 5, 'Modern', TRUE);
INSERT INTO legality VALUES (default, 5, 'Legacy', TRUE);
INSERT INTO legality VALUES (default, 5, 'Vintage', TRUE);
INSERT INTO legality VALUES (default, 5, 'Commander', TRUE);
INSERT INTO legality VALUES (default, 5, 'Oathbreaker', TRUE);
INSERT INTO legality VALUES (default, 5, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 5, 'Explorer', TRUE);
INSERT INTO legality VALUES (default, 5, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 5, 'Historic', TRUE);
INSERT INTO legality VALUES (default, 5, 'Pauper', TRUE);
INSERT INTO legality VALUES (default, 5, 'Penny', TRUE);

INSERT INTO legality VALUES (default, 6, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 6, 'Pioneer', TRUE);
INSERT INTO legality VALUES (default, 6, 'Modern', FALSE);
INSERT INTO legality VALUES (default, 6, 'Legacy', TRUE);
INSERT INTO legality VALUES (default, 6, 'Vintage', TRUE);
INSERT INTO legality VALUES (default, 6, 'Commander', TRUE);
INSERT INTO legality VALUES (default, 6, 'Oathbreaker', TRUE);
INSERT INTO legality VALUES (default, 6, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 6, 'Explorer', FALSE);
INSERT INTO legality VALUES (default, 6, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 6, 'Historic', FALSE);
INSERT INTO legality VALUES (default, 6, 'Pauper', TRUE);
INSERT INTO legality VALUES (default, 6, 'Penny', FALSE);

INSERT INTO legality VALUES (default, 7, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 7, 'Pioneer', FALSE);
INSERT INTO legality VALUES (default, 7, 'Modern', FALSE);
INSERT INTO legality VALUES (default, 7, 'Legacy', TRUE);
INSERT INTO legality VALUES (default, 7, 'Vintage', TRUE);
INSERT INTO legality VALUES (default, 7, 'Commander', TRUE);
INSERT INTO legality VALUES (default, 7, 'Oathbreaker', TRUE);
INSERT INTO legality VALUES (default, 7, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 7, 'Explorer', FALSE);
INSERT INTO legality VALUES (default, 7, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 7, 'Historic', FALSE);
INSERT INTO legality VALUES (default, 7, 'Pauper', TRUE);
INSERT INTO legality VALUES (default, 7, 'Penny', TRUE);

INSERT INTO legality VALUES (default, 8, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 8, 'Pioneer', FALSE);
INSERT INTO legality VALUES (default, 8, 'Modern', FALSE);
INSERT INTO legality VALUES (default, 8, 'Legacy', TRUE);
INSERT INTO legality VALUES (default, 8, 'Vintage', TRUE);
INSERT INTO legality VALUES (default, 8, 'Commander', TRUE);
INSERT INTO legality VALUES (default, 8, 'Oathbreaker', TRUE);
INSERT INTO legality VALUES (default, 8, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 8, 'Explorer', FALSE);
INSERT INTO legality VALUES (default, 8, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 8, 'Historic', FALSE);
INSERT INTO legality VALUES (default, 8, 'Pauper', TRUE);
INSERT INTO legality VALUES (default, 8, 'Penny', FALSE);

INSERT INTO legality VALUES (default, 9, 'Standard', FALSE);
INSERT INTO legality VALUES (default, 9, 'Pioneer', TRUE);
INSERT INTO legality VALUES (default, 9, 'Modern', TRUE);
INSERT INTO legality VALUES (default, 9, 'Legacy', TRUE);
INSERT INTO legality VALUES (default, 9, 'Vintage', TRUE);
INSERT INTO legality VALUES (default, 9, 'Commander', TRUE);
INSERT INTO legality VALUES (default, 9, 'Oathbreaker', TRUE);
INSERT INTO legality VALUES (default, 9, 'Alchemy', FALSE);
INSERT INTO legality VALUES (default, 9, 'Explorer', FALSE);
INSERT INTO legality VALUES (default, 9, 'Brawl', FALSE);
INSERT INTO legality VALUES (default, 9, 'Historic', FALSE);
INSERT INTO legality VALUES (default, 9, 'Pauper', TRUE);
INSERT INTO legality VALUES (default, 9, 'Penny', TRUE);

INSERT INTO rules VALUES (default, 1, 'Annihilator abilities trigger and resolve during the declare attackers step. The defending player chooses and sacrifices the required number of permanents before they declare blockers. Any creatures sacrificed this way won’t be able to block.', '2010-06-15');
INSERT INTO rules VALUES (default, 1, 'If a creature with annihilator is attacking a planeswalker, and the defending player chooses to sacrifice that planeswalker, the attacking creature continues to attack. It may be blocked. If it isn’t blocked, it simply won’t deal combat damage to anything.', '2010-06-15');
INSERT INTO rules VALUES (default, 1, 'Kozilek’s first ability triggers as you cast it, and that ability resolves before the spell itself. It resolves even if the spell is countered.', '2018-12-07');

INSERT INTO rules VALUES (default, 4, 'Annihilator abilities trigger and resolve during the declare attackers step. The defending player chooses and sacrifices the required number of permanents before they declare blockers. Any creatures sacrificed this way won’t be able to block.', '2010-06-15');
INSERT INTO rules VALUES (default, 4, 'If a creature with annihilator is attacking a planeswalker, and the defending player chooses to sacrifice that planeswalker, the attacking creature continues to attack. It may be blocked. If it isn’t blocked, it simply won’t deal combat damage to anything.', '2010-06-15');

INSERT INTO artists VALUES (default, 'Michael Komarck');
INSERT INTO artists VALUES (default, 'Milivoj Ćeran');
INSERT INTO artists VALUES (default, 'Christine Choi');
INSERT INTO artists VALUES (default, 'Mark Tedin');
INSERT INTO artists VALUES (default, 'Chris Rahn');
INSERT INTO artists VALUES (default, 'Caroline Gariba');
INSERT INTO artists VALUES (default, 'Keith Parkinson');
INSERT INTO artists VALUES (default, 'Zoltan Boros');
