DROP TABLE cards IF EXISTS;
DROP TABLE legality IF EXISTS;
DROP TABLE rules IF EXISTS;
DROP TABLE artists IF EXISTS;

CREATE TABLE cards (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(128),
  image_name    VARCHAR(128),
  mana_cost     VARCHAR(64),
  type_line     VARCHAR(64),
  description   VARCHAR(320),
  flavour       VARCHAR(192),
  stats         VARCHAR(8),
  artist        VARCHAR(64),
  set_name      VARCHAR(64),
  set_code      VARCHAR(8),
  serial_number SMALLINT,
  rarity        VARCHAR(16)
);

CREATE TABLE legality (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id       INTEGER,
  format_name   VARCHAR(64),
  is_legal      BOOLEAN
);

CREATE TABLE rules (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id   INTEGER,
  rule      VARCHAR(384),
  rule_date VARCHAR(32)
);

CREATE TABLE artists (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_name VARCHAR(38)
);
